### list developers 

GET http://localhost:3000/produtos

GET http://localhost:3000/produtos/3

POST http://localhost:3000/produtos
Content-Type:  application/json

{
    "nome":"Água Mineral",
    "dataDeValidade":"11/12/2026"
}

PATCH http://localhost:3000/produtos
